// Code generated by "stringer -type=tError -trimprefix=Error -output=error_string.go"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorInternal-1000]
	_ = x[ErrorOrderNotFound-1001]
}

const _tError_name = "InternalOrderNotFound"

var _tError_index = [...]uint8{0, 8, 21}

func (i tError) String() string {
	i -= 1000
	if i >= tError(len(_tError_index)-1) {
		return "tError(" + strconv.FormatInt(int64(i+1000), 10) + ")"
	}
	return _tError_name[_tError_index[i]:_tError_index[i+1]]
}
