// Code generated by "stringer -type=Error -trimprefix=Error"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorOrderNotFound-1]
}

const _Error_name = "OrderNotFound"

var _Error_index = [...]uint8{0, 13}

func (i Error) String() string {
	i -= 1
	if i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
