// Code generated by "stringer -type=SongLanguage -trimprefix=SongLanguage -output=songLanguage_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SongLanguagePersian-1]
	_ = x[SongLanguageEnglish-2]
	_ = x[SongLanguageArabic-3]
	_ = x[SongLanguageTurkish-4]
	_ = x[SongLanguageKurdish-5]
	_ = x[SongLanguageOther-6]
}

const _SongLanguage_name = "PersianEnglishArabicTurkishKurdishOther"

var _SongLanguage_index = [...]uint8{0, 7, 14, 20, 27, 34, 39}

func (i SongLanguage) String() string {
	i -= 1
	if i >= SongLanguage(len(_SongLanguage_index)-1) {
		return "SongLanguage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SongLanguage_name[_SongLanguage_index[i]:_SongLanguage_index[i+1]]
}
