// Code generated by "stringer -type=SongStatus -trimprefix=SongStatus -output=songStatus_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SongStatusPending-1]
	_ = x[SongStatusVerified-2]
	_ = x[SongStatusRejected-3]
	_ = x[SongStatusSold-4]
}

const _SongStatus_name = "PendingVerifiedRejectedSold"

var _SongStatus_index = [...]uint8{0, 7, 15, 23, 27}

func (i SongStatus) String() string {
	i -= 1
	if i >= SongStatus(len(_SongStatus_index)-1) {
		return "SongStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SongStatus_name[_SongStatus_index[i]:_SongStatus_index[i+1]]
}
