// Code generated by "stringer -type=SongSense -trimprefix=SongSense -output=songSense_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SongSenseHappyPositive-1]
	_ = x[SongSenseSadNegative-2]
}

const _SongSense_name = "HappyPositiveSadNegative"

var _SongSense_index = [...]uint8{0, 13, 24}

func (i SongSense) String() string {
	i -= 1
	if i >= SongSense(len(_SongSense_index)-1) {
		return "SongSense(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SongSense_name[_SongSense_index[i]:_SongSense_index[i+1]]
}
