// Code generated by "stringer -type=SongGenre -trimprefix=SongGenre -output=songGenre_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SongGenrePop-1]
	_ = x[SongGenreRap-2]
	_ = x[SongGenreRock-3]
	_ = x[SongGenreHipHop-4]
	_ = x[SongGenreTraditional-5]
}

const _SongGenre_name = "PopRapRockHipHopTraditional"

var _SongGenre_index = [...]uint8{0, 3, 6, 10, 16, 27}

func (i SongGenre) String() string {
	i -= 1
	if i >= SongGenre(len(_SongGenre_index)-1) {
		return "SongGenre(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SongGenre_name[_SongGenre_index[i]:_SongGenre_index[i+1]]
}
